### PR TITLE
RD-5435 Bump `sequelize` package to v6.21.3

### PR DESCRIPTION
**Pull request by qooban**
## Description

This PR bumps `sequelize` package version to the latest to fix [SQL Injection](http://security.snyk.io/vuln/SNYK-JS-SEQUELIZE-2959225) issue.

Once it is merged, I'm going to release new patch version of the `cloudify-ui-common` package.

## Screenshots / Videos
N/A

## Checklist
- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I verified that all tests and checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests
All local tests are passing. It's a minor version bump, so I don't expect big problems in Stage and Composer backends.

## Documentation
N/A

### CODE REVIEW

**Comment by qooban** [comment]
Closing as the newer version of `sequelize` is available and the bump will be handled in https://github.com/cloudify-cosmo/cloudify-ui-common/pull/128

**Review by NorbertAmartus — APPROVED** [review]
LGTM 🎉

**Review by NorbertAmartus — COMMENTED** [review]
Or maybe one question 😅 
`backend/package-lock.json` seems to not be updated, have you installed that package there or just updated `backend/package.json` file? 🤔

**Comment by qooban** [comment]
> Or maybe one question sweat_smile `backend/package-lock.json` seems to not be updated, have you installed that package there or just updated `backend/package.json` file? thinking

@NorbertAmartus There's no `backend/package-lock.json` file. `backend/package.json` is kind of artificial as it is not used to install dependencies 🙂 AFAIR it was added to make it possible to import from `cloudify-ui-common/backend`. I hope it'll be soon fixed when we'll have multiple independent common packages (ref. RD-1887).

**Pull request merged**
